locale = "en"
label = "English"
direction = "ltr"
weight = 1

title = "Kollin Mendoza"

[params]
  dateFormat = "2 January 2006"
  description = "Kollin Mendoza builds peaceful systems."
  mainSections = ["writings"]

[params.author]
  name = "Kollin Mendoza"
  image = "img/headshot.jpeg"
  headline = "Data Engineer, Programmer, Guy"
  bio = "Building peaceful systems."
  links = [
    { email = "mailto:kollin@hey.com" },
    { linkedin = "https://www.linkedin.com/in/kollin-mendoza/" },
    { github = "https://github.com/kamend0/" },
  ]

